#!/usr/bin/env sh

API_CHECK=$($(git diff HEAD~ --name-only | grep 'api/') | wc -c)
CLIENT_CHECK=$($(git diff HEAD~ --name-only | grep 'src/') | wc -c)

IYellow='\033[0;33m'
IGreen='\033[0;32m'

if [[ $API_CHECK -gt 1 && $CLIENT_CHECK -gt 1 ]]; then
    echo "${IYellow} 'Lint / Pretty / Build client & api'"
    npx npm run precommit
    echo "${IGreen} 'All steps succeeded for both client and api'"
    exit 0
fi

if [[ $API_CHECK -gt 1 ]]; then
    echo "${IYellow} 'Lint / Pretty / Build api'"
    npx npm run precommit:api
    echo "${IGreen} 'All steps succeeded for api'"
    exit 0
else
    echo "${IGreen} API already up to date"
fi

if [[ $CLIENT_CHECK -gt 1 ]]; then
    echo "${IYellow} 'Lint / Pretty / Build client'"
    npx npm run precommit:client
    echo "${IGreen} 'All steps succeeded for client'"
    exit 0
else
    echo "${IGreen} Client already up to date"
fi
