#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

declare API_CHECK=$(git diff HEAD~ --name-only | grep 'api/')
declare CLIENT_CHECK=$(git diff HEAD~ --name-only | grep 'src/')

echo $API_CHECK $CLIENT_CHECK

IYellow='\033[0;93m'
IGreen='\033[1;92m'

if [ $API_CHECK ] && [ $CLIENT_CHECK ]
then
    echo ${IYellow} 'Lint / Pretty / Build client & api'
    npx npm run precommit
    echo ${IGreen} 'All steps succeeded for both client and api'
    exit 0
fi

if $API_CHECK
then
    echo ${IYellow} 'Lint / Pretty / Build api'
    npx npm run precommit:api
    echo ${IGreen} 'All steps succeeded for api'
    exit 0
fi

if [ $CLIENT_CHECK ]
then
    echo ${IYellow} 'Lint / Pretty / Build client'
    npx npm run precommit:client
    echo ${IGreen} 'All steps succeeded for client'
    exit 0
fi
